[mysql-master]
host = "localhost"
user = "root"
password = "123456"
database = "cow_dev"

[redis-master]
host = "localhost"
port = 6379
password = ""

[http-web1-9001]
ip = "localhost"
port = 9001
path = "/ping"
