# [mysql-master]
# host = "localhost"
# user = "root"
# password = "123456"
# database = "cow_dev"

# [redis-master]
# host = "localhost"
# port = 6379
# password = ""

# [http-web1-9001]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-api1-9001]
# ip = "localhost"
# port = 9002
# path = "/"

# [http-web1-9002]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-web1-9003]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-web1-9004]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-web2-9001]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-web2-9002]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-web2-9003]
# ip = "localhost"
# port = 9001
# path = "/ping"

# [http-web2-9004]
# ip = "localhost"
# port = 9001
# path = "/ping"
