[db]
host = "localhost"
databse = "eagle"

[http-web1-9001]
ip = "localhost"
port = 9001
path = "/ping"

[http-api1-9001]
ip = "localhost"
port = 9002
path = "/"

[redis-master]
host = "localhost"
port = 6379
password = ""
